create table user_table (
  is_user_enabled boolean default true not null,
  user_id bigint generated by default as identity,
  user_role varchar(10) default 'CUSTOMER' not null check (user_role in ('ADMIN','CUSTOMER','ANALYST')),
  user_email varchar(30) not null unique,
  user_password varchar(255) not null,
  primary key (user_id)
);

alter table if exists user_table add constraint user_email_ind unique (user_email);
