create table loan_application_table (
  loan_application_id bigint generated by default as identity,
  loan_application_amount numeric(6,2) not null,
  loan_application_created timestamp(6) default CURRENT_TIMESTAMP not null,
  loan_application_decisioned timestamp(6),
  loan_application_percent numeric(5,4) not null,
  loan_application_status varchar(15) default 'NEW' not null
    check (loan_application_status in ('NEW','UNDER_REVIEW','APPROVED','REJECTED','EXPIRED')),
  loan_application_term numeric(3,0) not null,
  loan_application_customer_id bigint not null,
  primary key (loan_application_id)
);

alter table if exists loan_application_table
	add constraint loan_customer_fk
  foreign key (loan_application_customer_id)
  references customer_profile_table;

create index loan_application_status_ind
	on loan_application_table (loan_application_status);
create index loan_application_created_ind
	on loan_application_table (loan_application_created);
create index loan_application_customer_ind
	on loan_application_table (loan_application_customer_id, loan_application_created);
